noun1= input(" please enter a noun")
noun2=input(" please enter a wacky state")
print("A",noun1,"in",noun2, "was arersted this mornig")
verb1=input(" please enter a verb")
noun3=input("please enter a noun:")
propernoun1=input("please enter a proper noun:")
verb2=input("please enter a verb:")
noun4=input("please enter a noun:")
verb3=input("please enter a verb:")
noun5=input("please enter a noun:")
body-part1=input("please enter a body part:")
print("After he ",verb1, "ain front of" ,noun3,propernoun1, "had a history of",verb2,)